#page title
page_title                                : Fileball                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1558391784                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/filebox-logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Fileball - Play with files                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A modern app designed for iOS and iPadOS. Offers file management, music player, video player and text editor.
app_description_cn                        : 一款为iOS、iPadOS设计的现代化应用，提供了文件管理、音乐播放器、视频播放器
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.




# Information About Yourself
your_name                                 : 
your_link                                 : 
your_city                                 :                                 
email_address                             : filebox.app@outlook.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
twitter_username                          : FileboxApp
telegram_username                          : FileballApp
# github_username                           : emilbaehr
# youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : File Management
    description                           : Manage your local files - Edit, Delete, View, Share, Move, Unzip.
    fontawesome_icon_name                 : folder
    
  - title                                 : Remote Connection
    description                           : Connect with your MAC, PC, NAS, FTP, SMB, SFTP
    fontawesome_icon_name                 : hdd

  - title                                 : Music Player
    description                           : Play with your loved songs with filebox
    fontawesome_icon_name                 : music

  - title                                 : Movie Player
    description                           : More video type supported - MKV, FLV, RMVB and so on
    fontawesome_icon_name                 : film
  
  - title                                 : Customizeable
    description                           : Everything you can imagine is customizeable.
    fontawesome_icon_name                 : star

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.


# Feature List                            Edit, add or remove features to be presented.
features_cn                                  :

  - title                                 : 文件管理
    description                           : 管理您的本地与远程文件 - 编辑、删除、查看、分享、移动、解压
    fontawesome_icon_name                 : folder
    
  - title                                 : 远程连接
    description                           : 连接您的MAC、PC、NAS、 FTP、SMB、SFTP
    fontawesome_icon_name                 : hdd

  - title                                 : 音乐播放器
    description                           : 漂亮的本地音乐播放器
    fontawesome_icon_name                 : music

  - title                                 : 视频播放器
    description                           : 播放更多视频格式 - MKV、FLV、RVMB等
    fontawesome_icon_name                 : film
  
  - title                                 : 自定义
    description                           : 任何您能想到的都可自定义
    fontawesome_icon_name                 : star

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/artwork.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FFCA28"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

include: [".well-known"]

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown